### PR TITLE
Improve flow by focusing the SSH iframe when the SSH modal is opened

### PR DESCRIPTION
**Pull request by WilliamsJack**
Users no longer have to click on the SSH iframe before they can start typing commands.

### CODE REVIEW

**Comment by WilliamsJack** [comment]
The new focusModalContent() method should be useful if you want to automatically focus the content of any other modals.

I'd recommend against focusing config editors by default as users may accidentally edit configs.

**Comment by Conr86** [comment]
Good idea!

However, I think there's possibly a better way to do this. If we defined a "focus" class of sorts that can be applied to any modal we want to focus automatically (SSH for example, but not config editor, as you said).

I haven't tested it, but something like this:
```js
$(".modal-focus").on('shown.bs.modal', function () {
    this.focus();
});
```

**Comment by WilliamsJack** [comment]
The modal should already be focused when opened. For this to work we need to focus on the iframe inside the modal, not the modal itself. Something similar to what you suggested could work, but we'd still need to specify what we want to focus on inside the modal.

**Comment by Conr86** [comment]
Possibly something like this then?

```js
$("#sshModal").on('shown.bs.modal', function () {
    $("ssh_iframe").focus();
});
```
That's obviously only for the SSH modal though, not sure of the nicest way to make it generic.

**Comment by WilliamsJack** [comment]
All modals trigger the event. If they have an element to focus specified in a custom data attribute in HTML, that element will be focused.

**Pull request merged**
